global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'tomcat'
  static_configs:
  - targets: ['app:8080']
- job_name: 'webrun'
  metrics_path: /hello-world/metrics
  static_configs:
    - targets: ['app:8080']
- job_name: 'otel'
  static_configs:
    - targets: ['otel:8888', 'otel:8889']